development:
  url: https://localhost:4000
  future: true
  fathom:
    site_id: FWVZGVUN
    events:
      workshop_ticket: 63NSE21U

staging:
  url: https://dev.masilotti.com
  fathom:
    site_id: FWVZGVUN
    events:
      workshop_ticket: XXXXXXXX

production:
  url: https://masilotti.com
  fathom:
    site_id: QNURQQHD
    events:
      workshop_ticket: AWZOJS4N

preview_links:
  site_id: 755

# TODO: Move to config/initializers.rb.
collections:
  hotwire:
    sort_direction: descending
    output: true
  snippets:
    output: false

# TODO: Move to config/initializers.rb.
feed:
  collections:
    hotwire:
      path: /hotwire.xml

# TODO: Categories, tags, or custom taxonomies for turbo-ios series.
# https://www.bridgetownrb.com/docs/resources#taxonomies
